language: node_js
node_js:
  - 12.13.0
addons:
  - chrome: stable
jobs:
  include:
    - stage: test
      script:
        - echo 'Running tests..'
        - npm run test
    - stage: deploy
      script:
        - echo 'Deploying'
        - |
          set -ev
          ENCRYPTED_KEY_VAR="encrypted_${ENCRYPTION_LABEL}_key"
          ENCRYPTED_IV_VAR="encrypted_${ENCRYPTION_LABEL}_iv"
          ENCRYPTED_KEY=${!ENCRYPTED_KEY_VAR}
          ENCRYPTED_IV=${!ENCRYPTED_IV_VAR}
          
          $(npm bin)/set-up-ssh --key "$ENCRYPTED_KEY" \
                                --iv "$ENCRYPTED_IV" \
                                --path-encrypted-key "travis/github_deploy_key.enc"
          $(npm bin)/update-branch --commands "ng deploy --base-href ./" \
                              --commit-message "Deploying to github pages" \
                              --directory "dist" \
                              --distribution-branch "gh-pages" \
                              --source-branch "master" \
stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = master
env:
  global:
  - ENCRYPTION_LABEL: "58a1aa26d61a"
  - secure: rEcDiR+RowI87H/BE5blDMOZapO4RTlYJyCZy8AEcm5qg33EGqWE1jli6I46VJDuqDQoaM62zMh7Vnksf9CarHNaBzoaAAqLwtJP7lGS3xGJDfbeVfaYSu9faJdskEOUsJY1usMBrw0ach3g3RUN6k7umv8omcwdc/bP7WdlcPipZu2fJZC4mHSKf+K4H/HxotWwKvXdL4Tzjcq5ZDXd2yObIFbfYaP34m+N82JBEuz6bK41TK45hCitTXVLq3Av9Ymuc8pxvFEgRBrAL/6f7FWTTxliekxNNbAHLXodVM7S47iMLWlKNAyj9qlDhfX5IHU0XGLUwOKjBpL6Xm64TpZR3DYVHJMF40gtdxgI2jA2lFIHuJrkHTSvXHuEwetjXOGpU0Ir97Q6RrPKjohfdDiRmRNxOqM6oGKxGbAVrpr4sVBqJ2Tvoj23hEwbfP6LfEF+SDbjc7Drw7Ho3SMaJRKYY4VTLCNLFN6ackbvgtoCjDmYxB4S2oZneYHW5pRJbY+feb4bilPQDui7N/QwPTlJmbXGHmjqsMM/eoUwjKRffb8HVnvpQvOSXpqvfKsPXQQFXKbiyCEcMCEn3MYYNAYbn1CrM2TX675Zw+MlAE9v3hbP6A5dmpj1Fa0/+Zn6K8i7MD+VV3eNi16X7WoZBT19S1fgZgMizPwZITicPg0=
  - secure: "AHrQtI4I7zA+ejdbCSMhHVA4jwxTW8VlM6rJFbTHyB/0LldjvziVcWzzD43kHHAMh5aMhFQsMC5O64sQ+6DXjKWejcLVyGW6d3NEoBpkKosBokiuI9P1kkzRon4QYVmWMcxDzfDwp9PPx/Yh52mF6Ovn/tWCuMksda5Yd1KWdt+Mf9qu0l3Mn1dXmrhJihqoldC9W/gu3nkeu/qGH2dSExQLfdKJuOotZxd2fXkpKouR3QlGCenmysmdWvOHXCiezYcOsoNN3yk3jhS3VP5KSPaeWVTW5M+muTwDp12tFq2VKNcXsJ/R9kfNiRUf7wHMfTyNqL2xrTsaWgNd2E9SXwFcRaLj6wi1cJyO4GjQ00a2jnGc2M/LBty8rvB32U7f3R2Nivn9kxqMCEuzpyeFsp2FaJbkWMqryFIkBhLuTprf4rV18ZV9cRtAwuMePj9ioTfJK+aco7mvvAz9y6I48EglaThbZz9nlSvGsodVUtT11DY/pAVPpV1w6SaEqWHs1fBcCtWkjZ/fnlmE1wVVbpwcULZp8krG7IHXIPKyAC55PT2ISicwHbA38kfbMciqCFJxzbkTAz8McNERo0i3mPW1bugSDtpem9xUfzI+nNlq/K62/BINebgoYDFl/GyFoS576gQOdZH/OIty5kmXRfHzG9YzXFFaX5PuXdl1JPU="